export const productPriceCatalog = [
  { name: 'Semaglutide 1mg', price: 589 },
  { name: 'Semaglutide 3mg', price: 789 },
  { name: 'Semaglutide 7mg', price: 889 },
  { name: 'Semaglutide 10mg', price: 889 },
  { name: 'Semaglutide Microdose', price: 489 },
  { name: 'Tirzepatide 8mg', price: 699 },
  { name: 'Tirzepatide 24mg', price: 899 },
  { name: 'Tirzepatide 52mg', price: 1299 },
  { name: 'Tirzepatide 60mg', price: 1299 },
  { name: 'Tirzepatide Microdose', price: 599 },
  { name: 'Lipo-Mino One Month', price: 374 },
  { name: 'Lipo-Mino 3 Months', price: 889 },
  { name: 'NAD+ One Month', price: 374 },
  { name: 'NAD+ 3 Months', price: 889 },
  { name: 'GHK-Cu 3 Months', price: 748 },
  { name: 'GHK-Cu One Month', price: 374 },
  { name: 'Sermorelin Two Months', price: 599 },
  { name: 'Sermorelin One Month', price: 374 },
  { name: 'Glutathione Four Months', price: 549 },
  { name: 'Glutathione Two Months', price: 374 },
  { name: 'Nutrition Consultation 12 months', price: 1379.16 },
  { name: 'Nutrition Consultation 6 months', price: 799.86 },
  { name: 'Nutrition Consultation 3 months', price: 449.01 },
  { name: 'Nutrition Consultation 1 month - Non GLP-1 Clients', price: 250 },
  { name: 'Nutrition Consultation 1 month', price: 199 },
  { name: 'Beauty Boost - Hair, Skin and Nails Essentials', price: 24.9 },
  { name: 'Bloat Away - Probiotic 40 Billion with Prebiotics', price: 24.9 },
  { name: 'Bone & Heart Support', price: 24.9 },
  { name: 'Brain & Focus Formula', price: 24.9 },
  { name: 'Complete Multivitamin', price: 24.9 },
  { name: 'Detox Now - Refresh, Cleanse & Glow', price: 24.9 },
  { name: 'Diet Drops Ultra', price: 24.9 },
  { name: 'Gut Boost Pro & Smooth Digestion', price: 24.9 },
  { name: 'Love Me Now - Maca Plus', price: 24.9 },
  { name: 'Omega-3 EPA 180mg + DHA 120mg', price: 24.9 },
  { name: 'Vitamin D3 2,000 IU', price: 24.9 },
  { name: 'Magnesium Glycinate', price: 24.9 },
  { name: 'Energy Strips', price: 29.9 },
  { name: 'L-Glutamine Powder', price: 29.9 },
  { name: 'Sleep Strips', price: 29.9 },
  { name: 'Berberine + & Weight Balance', price: 45 },
  { name: 'Berberine+ & Pierde Peso', price: 45 },
  { name: 'Hydraglow Powder (Lemonade)', price: 34.99 },
  { name: 'Colon Gentle Cleanse', price: 33.9 },
  { name: 'Colostrum Capsules', price: 33.9 },
  { name: 'Creatine Monohydrate', price: 33.9 },
  { name: 'Fat Burner & Appetite Control', price: 33.9 },
  { name: 'Chocolate - Collagen Peptides Grass-Fed Powder', price: 39.9 },
  { name: 'NAD+ Cellular Energy & Anti-Aging', price: 39.9 },
  { name: 'Unflavored - Collagen Peptides Hydrolyzed Grass-Fed', price: 39.9 },
  { name: 'Vanilla - Collagen Peptides Creamer Grass-Fed Powder', price: 39.9 },
  { name: 'Chocolate - Whey Protein Isolate Advanced 100%', price: 49.9 },
  { name: 'Vanilla - Whey Protein Isolate Advanced 100%', price: 49.9 },
  { name: 'Shipping', price: 5 },
  { name: 'SlimBoost', price: 89 },
  { name: 'Detox Tea', price: 15.99 },
]
